version: '3.9'

volumes:
   mapproxy_cache_data:

services:

   mapproxy:
      image: kartoza/mapproxy
      build:
        context: .
        args:
          MAPPROXY_VERSION: ''
          IMAGE_VERSION: '3.11.5'
      volumes:
        # If MULTI_MAPPROXY=true then mount to /multi_mapproxy otherwise mount to /mapproxy
        - ./mapproxy_configuration:/mapproxy
        - mapproxy_cache_data:/cache_data
      ports:
        - "8082:8080"
      restart: always
      environment:
        - PRODUCTION=true
        - PROCESSES=20
        - CHEAPER=16
        - THREADS=10
        - MAPPROXY_USER_ID=1000
        - MAPPROXY_GROUP_ID=1000
        - MULTI_MAPPROXY=false
        - ALLOW_LISTING=True
        - LOGGING=true

